name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "v**"

env:
  DENO_VERSION: 1.46

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Lint
        run: deno lint

      - name: Format
        run: deno fmt --check

      - name: Type Check
        run: deno check src/*.ts

      - name: Fixtures
        run: deno task fixtures

      - name: Test
        run: deno test --allow-read --no-check --coverage

      - name: Report
        run: deno coverage

  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Make Fixtures
        run: deno task fixtures 12

      - name: Run Benchmark
        run: deno bench --allow-read --no-check
